# 第一行为通用配置
spring:
  profiles:
    # active=谁，就激活哪个环境6y
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: user-center
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  appname: user-center
  author: qiaotong
  version: 0.1
rocketmq:
  name-server: 127.0.0.1:9876
---
# 开发环境
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ad25f90b-b56d-4dfa-80a7-c503830cea33
        cluster-name: NX
server:
  port: 8002
---
# 生产环境
spring:
  profiles: prod
server:
  tomcat:
    max-connections: 1000
    max-threads: 300