server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ad25f90b-b56d-4dfa-80a7-c503830cea33
        cluster-name: NX
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_route
          uri: lb://user-center
          predicates:
            - Path=/users/**
        - id: content_route
          uri: lb://content-center
          predicates:
            - Path=/shares/**,/admin/**
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      #      抽样率，0.1(10%)，这意味着90%的数据都会被丢弃
      probability: 1.0
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'