# 第一行为通用配置
spring:
  profiles:
    # active=谁，就激活哪个环境
    active: dev
    include:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8
  application:
    name: content-center
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output:
            producer:
              transactional: true
              group: tx-add-bonus-group
      bindings:
        output:
          destination: add-bonus
    #   nacos配置
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: ad25f90b-b56d-4dfa-80a7-c503830cea33
        cluster-name: NX
    #   sentinel负载均衡配置
    sentinel:
      transport:
        # 指定控制台的地址
        dashboard: localhost:8080
      # push模式规则持久化
      datasource:
        # 名称随意
        flow:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-flow-rules
            # 组
            groupId: DEFAULT_GROUP
            # 要读取的配置数据类型
            data-type: json
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            rule-type: flow
      filter:
        enabled: true

#actuator配置
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  appname: content-center
  author: qiaotong
  version: 0.1
#消息中间件
rocketmq:
  # 设置名称服务
  name-server: 127.0.0.1:9876
  producer:
    group: add-bonus-group
jwt:
  secret: aaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrsssttt
  expire-time-in-second: 1209600
# 开发环境
server:
  port: 8081
user-center:
  ribbon:
    NFloadBalancerRuleClassName: com.mynotes.contentcenter.config.NacosWeightedRule
ribbon:
  eager-load:
    enabled: true
feign:
  client:
    config:
      #全局日志打印配置
      default:
        loggerLevel: full
        requestInterceptors:
          - com.mynotes.contentcenter.feignclient.interceptor.TokenRequestInterceptor
  #使用httpclient发送请求，而不是原生的urlConnection
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  #为feign整合sentinel
  sentinel:
    enabled: true
logging:
  level:
    com.mynotes.contentcenter.feignclient.UserCenterClient: debug
    com.alibaba.nacos.client.config.impl.ClientWorker: warn
---
# 生产环境
spring:
  profiles: prod
server:
  tomcat:
    max-connections: 1000
    max-threads: 300