# 第一行为通用配置
spring:
  profiles:
    # active=谁，就激活哪个环境
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: user-center
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: add-bonus
          group: binder-group
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
#      抽样率，0.1(10%)，这意味着90%的数据都会被丢弃
      probability: 1.0
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  appname: user-center
  author: qiaotong
  version: 0.1
rocketmq:
  name-server: 127.0.0.1:9876
jwt:
  secret: aaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrsssttt
  expire-time-in-second: 1209600
#  日志配置
logging:
  level:
    org.springframework.cloud.sleuth: debug
feign:
  client:
    config:
      #全局日志打印配置
      default:
        loggerLevel: full
---
# 开发环境
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ad25f90b-b56d-4dfa-80a7-c503830cea33
        cluster-name: NX
server:
  port: 8001
---
# 生产环境
spring:
  profiles: prod
server:
  tomcat:
    max-connections: 1000
    max-threads: 300